### ISSUE TITLE
INDEX ERROR

### ISSUE THREAD

**Issue by LucasHisabf** [LoffyNora/TikTok-ViewBot#5]
```
`[hujark@Anderson2005:~/TikTok-lucas$ python3 main.py
Solving captcha..
Cant get services, retrying...
Solving captcha..
Traceback (most recent call last):
  File "/home/hujark/TikTok-lucas/main.py", line 161, in <module>
    Z.get_table()
  File "/home/hujark/TikTok-lucas/main.py", line 76, in get_table
    else:print('Cant get services, retrying...');self.send_captcha();time.sleep(2)
  File "/home/hujark/TikTok-lucas/main.py", line 46, in send_captcha
    captcha_solve = self.solve_captcha('captcha.png')[1]
  File "/home/hujark/TikTok-lucas/main.py", line 61, in solve_captcha
    solved_text = request['ParsedResults'][0]['ParsedText']
IndexError: list index out of range](url)`
```

**Comment by LoffyNora** [comment]
fixed
